feat: use the new ABI for mech
valory-xyz/ai-registry-mech-frontend pull request #45
Opened 2023-11-01 19:58 UTC by mohandast52

- should work the same as before
- updated old mech ABI with a new one

<img width="1437" alt="Screenshot 1" src="https://github.com/valory-xyz/ai-registry-mech-frontend/assets/22061815/49f972f2-3dd8-44cf-a21f-5aebb7f21983">

<img width="1362" alt="Screenshot 2" src="https://github.com/valory-xyz/ai-registry-mech-frontend/assets/22061815/993fe8f5-5864-45f9-a8b8-3d630e562aaf">

2023-11-01 20:04 UTC, kupermind commented on common-util/Contracts/index.jsx
> +    const url = 'https://api.studio.thegraph.com/query/57238/mech/v0.0.1';
Is this the updated query accounting for two AgentFactories?

2023-11-01 20:05 UTC, kupermind commented on components/Home/Mech/index.jsx
> -import { NEW_MECH_ABI } from 'common-util/AbiAndAddresses/newMech';
This file can be removed then.

2023-11-01 20:05 UTC, kupermind approved these changes

2023-11-03 09:45 UTC, oaksprout requested changes

2023-11-03 09:45 UTC, oaksprout commented on components/Home/Mech/index.jsx
> +          message={`We have encountered challenges with data retrieval, resulting in a temporary unavailability of older requests. NOTE: We only load the latest ${LATEST_BLOCK_COUNT} blocks`}
```suggestion
          message={`We only load the latest ${LATEST_BLOCK_COUNT} blocks due to data availability issues.`}
```

2023-11-03 09:45 UTC, oaksprout commented on components/Home/Mech/index.jsx
> +          message={`We have encountered challenges with data retrieval, resulting in a temporary unavailability of older requests. NOTE: We only load the latest ${LATEST_BLOCK_COUNT} blocks`}
@mohandast52 we should also add a message to the empty state on this list.

```
No requests
<br />
Only loading latest LATEST_BLOCK_COUNT block(s). [See earlier events](https://gnosisscan.io/address/${mechAddress}#events).
```

2023-11-11 15:26 UTC, oaksprout approved these changes

2023-11-13 15:57 UTC, oaksprout commented
@mohandast52 looks like once the conflicts are resolved we can merge

2023-11-14 08:43 UTC, merged